// La página que la consola sirve al teléfono. Autocontenida (sin CDNs: la
// consola es el único servidor de la red que el teléfono va a alcanzar).
#pragma once

static const char WEBUI_HTML[] =
"<!doctype html><html lang=es><head><meta charset=utf-8>"
"<meta name=viewport content=\"width=device-width,initial-scale=1\">"
"<title>WiiU Cast</title><style>"
":root{--bg:#0e141b;--card:#151d26;--line:#263442;--ink:#e4ebf2;--dim:#94a5b6;--ac:#3fb3e6}"
"*{box-sizing:border-box}"
"body{margin:0;padding:24px 16px 48px;background:var(--bg);color:var(--ink);"
"font:16px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif}"
".w{max-width:520px;margin:0 auto}"
"h1{font-size:1.5rem;margin:0 0 4px;letter-spacing:-.02em}"
".sub{color:var(--dim);font-size:.9rem;margin:0 0 24px}"
".card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px;margin-bottom:16px}"
"label{display:block;font-size:.8rem;text-transform:uppercase;letter-spacing:.08em;color:var(--dim);margin-bottom:8px}"
"input{width:100%;padding:12px;font-size:16px;background:#0e141b;color:var(--ink);"
"border:1px solid var(--line);border-radius:8px}"
"input:focus{outline:2px solid var(--ac);outline-offset:1px;border-color:transparent}"
"button{width:100%;margin-top:12px;padding:14px;font-size:1rem;font-weight:600;"
"background:var(--ac);color:#06121a;border:0;border-radius:8px;cursor:pointer}"
"button:active{opacity:.8}"
"button.sec{background:transparent;color:var(--ink);border:1px solid var(--line);margin-top:8px}"
".row{display:flex;gap:8px}.row button{margin-top:0}"
".st{display:flex;align-items:center;gap:10px;font-size:.9rem}"
".dot{width:8px;height:8px;border-radius:50%;background:var(--dim);flex:none}"
".dot.on{background:#4cc38a}"
"#now{color:var(--dim);font-size:.85rem;word-break:break-all;margin-top:8px;min-height:1.2em}"
".hint{color:var(--dim);font-size:.8rem;margin-top:16px;text-align:center}"
"</style></head><body><div class=w>"
"<h1>WiiU Cast</h1>"
"<p class=sub>Receptor de medios local</p>"
"<div class=card>"
"<label for=u>URL del video</label>"
"<input id=u type=url inputmode=url placeholder=\"http://...\" autocomplete=off>"
"<button onclick=cast()>Reproducir en la TV</button>"
"</div>"
"<div class=card>"
"<div class=st><span class=dot id=d></span><span id=s>Conectando...</span></div>"
"<div id=now></div>"
"<div class=row style=margin-top:12px>"
"<button class=sec onclick=\"cmd('pause')\">Pausa</button>"
"<button class=sec onclick=\"cmd('stop')\">Detener</button>"
"</div>"
"</div>"
"<p class=hint>La consola y este telefono estan en la misma red.</p>"
"</div><script>"
"async function cast(){const u=document.getElementById('u').value.trim();if(!u)return;"
"await fetch('/cast',{method:'POST',body:u});poll()}"
"async function cmd(c){await fetch('/cmd?a='+c,{method:'POST'});poll()}"
"async function poll(){try{const r=await fetch('/status');const j=await r.json();"
"document.getElementById('s').textContent=j.state;"
"document.getElementById('d').className='dot on';"
"document.getElementById('now').textContent=j.url||''}"
"catch(e){document.getElementById('s').textContent='Sin conexion';"
"document.getElementById('d').className='dot'}}"
"poll();setInterval(poll,2000);"
"</script></body></html>";
